
spring:
  datasource:
    username: root
    password: W6o6aOirRdDuxCk
    url: jdbc:mysql://localhost:3306/messages
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# IBM MQ Connection Configuration
ibm:
  mq:
    queue-manager: 506762a034e5
    channel: DEV.APP.SVRCONN
    connName: localhost(1414),127.0.0.1(1414),ibmmq(1414)
    user: app
    password: passw0rd
    queue: TEST.QUEUE